//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMaintenanceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCodeNumber
    {
        public SiteCodeNumber()
        {
            this.CallLogs = new HashSet<CallLog>();
            this.Sites = new HashSet<Site>();
            this.Staffs = new HashSet<Staff>();
            this.ServiceTiers = new HashSet<ServiceTier>();
        }
    
        public int siteCode { get; set; }
    
        public virtual ICollection<CallLog> CallLogs { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<ServiceTier> ServiceTiers { get; set; }
    }
}
