//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMaintenanceApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteMantenanceEntities : DbContext
    {
        public SiteMantenanceEntities()
            : base("name=SiteMantenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CallLog> CallLogs { get; set; }
        public DbSet<Level> Levels { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<SiteAccountManager> SiteAccountManagers { get; set; }
        public DbSet<SiteCodeNumber> SiteCodeNumbers { get; set; }
        public DbSet<SiteState> SiteStates { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Territory> Territories { get; set; }
        public DbSet<ServiceTier> ServiceTiers { get; set; }
    }
}
