//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteMaintenanceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAccountManager
    {
        public SiteAccountManager()
        {
            this.Staffs = new HashSet<Staff>();
            this.Territories = new HashSet<Territory>();
        }
    
        public string accountManager { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Territory> Territories { get; set; }
    }
}
